name: JH Make kernel cache

on:
  push:
  schedule:
    - cron: '0 */8 * * *' # Scheduled every 8 hours
  workflow_call:
    inputs:
      config: 
        type: string
        required: true
      tag:
        type: string
        required: true
      release:
        type: string
        required: false
        default: 'nightly'
      version:
        type: string
        required: true
    secrets:
      token:
        required: true
      SSH_KEY:
        required: true
      SSH_KNOWNHOSTS_UPLOAD:
        required: true

jobs:
  prepare:
    name: "Make JSON"
    if: ${{ github.repository_owner == 'jethome-iot' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.json.outputs.JSON_CONTENT }}
    steps:
      - name: Checkout Armbian Framework
        uses: actions/checkout@v3
        with:
          repository: jethome-iot/armbian-build
          ref:  ${{ inputs.tag == null && 'main-jethub' || inputs.tag }}
          fetch-depth: 1
          clean: false # true is default. it *will* delete the hosts /dev if mounted inside.
          path: build

      - name: Checkout Armbian OS
        uses: actions/checkout@v3
        with:
          repository: jethome-iot/armbian-os
          ref:  main
          fetch-depth: 1
          clean: false # true is default. it *will* delete the hosts /dev if mounted inside.
          path: os

      - name: Build JSON
        id: json
        run: |
          # Make a list of valid pairs from our config
          echo 'JSON_CONTENT<<EOF' >> $GITHUB_OUTPUT
          for BRANCH in legacy current edge; do
              FILES=$(cat os/targets/jethub*.conf | grep $BRANCH | grep -v "^$" | grep -v "^#" | sed -n 'p' | cut -d " " -f1 | uniq)
              if [ -z "${FILES}" ]; then
                continue
              fi
              LINUXVERSIONS=$(cat os/targets/jethub*.conf | grep $BRANCH | grep -v "^$" | grep -v "^#" | sed -n 'p' | awk '{print $3};' | sort | uniq | tr '\n' ' ' | sed 's/ /,/g')
              while IFS= read -r line; do
                BOARDFAMILY=$(cat build/config/boards/$line.* | grep BOARDFAMILY | cut -d'"' -f2)
                BOARD=$line
                source build/config/boards/$line.conf 2> /dev/null || true
                source build/config/boards/$line.wip 2> /dev/null || true
                source build/config/boards/$line.tvb 2> /dev/null || true
                source build/config/sources/families/${BOARDFAMILY}.conf 2> /dev/null || true

                # runner management. current set to "high" local runners
                RUNNER=ubuntu-latest
                [[ "${ARCH}" == arm64 ]] && RUNNER=aarch64
                [[ "${BRANCH}" == current ]] && RUNNER=high
                [[ "${BRANCH}" == edge ]] && RUNNER=high
                [[ "${BRANCH}" == legacy ]] && RUNNER=high
                echo "${LINUXFAMILY}:${BOARDFAMILY}:${BRANCH}:${line}:${RUNNER}:${LINUXVERSIONS}"
              done <<< "$FILES"
          done | sort | uniq | sort -u -t: -k1,3 | cut -d":" -f3,4,5,6 | sort | uniq | sed "s/:/ /g" | awk '{ printf "%s%s%s%s\n", "{\"board\":\""$2"\",", "\"branch\":\""$1"\",", "\"runner\":\""$3"\",", "\"linux\":\""$4"\"}" }' | jq -s >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  kernel:
    if: ${{ github.repository_owner == 'jethome-iot' }}
    needs: [ prepare ]
    strategy:
      fail-fast: false # let other jobs try to complete if one fails
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.matrix) }}
        
    runs-on: "${{ matrix.runner }}"
    
    name: "${{ matrix.board }} ${{ matrix.branch }} ${{ matrix.runner }}"
    env:
      BRANCH: "${{ matrix.branch }}"
      BOARD: "${{ matrix.board }}"
      OCI_TARGET_BASE: "ghcr.io/${{ github.repository }}/" # This is picked up by the Docker launcher automatically
    steps:

      # Login to ghcr.io, for later uploading rootfs to ghcr.io
      - name: Docker Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # GitHub username or org
          password: ${{ secrets.GITHUB_TOKEN }}    # GitHub actions builtin token. repo has to have pkg access.
 
      - name: Checkout build repo
        uses: actions/checkout@v3 # We don't need to clone git, really. A wget would suffice for GH-hosted runners. But using clone is better for Igor-hosted runners.
        with:
          repository: jethome-iot/armbian-build
          ref: ${{ inputs.tag == null && 'main-jethub' || inputs.tag }}
          fetch-depth: 1
          clean: false # true is default. it *will* delete the hosts /dev if mounted inside.

      - name: Build Kernel ${{env.BOARD}}:${{env.BRANCH}}
        id: kernel
        run: |
          # BRANCH and BOARD are in the env, but Docker doesn't know that; (sudo has --preserve-env). So we need to pass them as args.
          # SHARE_LOG=yes to share logs to pastebin
          VER="${{ inputs.version == null && 'nightly' || inputs.version }}"
          if [ ${VER} == "nightly" ]; then
            VER=$(cat VERSION)
          fi
          echo ${VER} > userpatches/VERSION
          sudo rm -rf output/debs/* || true
          bash ./compile.sh kernel "BRANCH=${{env.BRANCH}}" "BOARD=${{env.BOARD}}" SHARE_LOG=no CLEAN_LEVEL="alldebs" ARTIFACT_IGNORE_CACHE=yes FORCE_ARTIFACTS_DOWNLOAD="yes"
          ls -l output/debs/
          echo "files<<EOF" >> $GITHUB_OUTPUT
          ls output/debs/linux-*.deb >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          du output


      - name: "Generate key id" # We need this in case we run multiple runners on one machine
        shell: bash
        run: echo "RANDOM=ID_$((RANDOM%1000000))" >> $GITHUB_ENV

      - name: Install SSH key for storage
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: ${{ env.RANDOM }}
          known_hosts: ${{ secrets.SSH_KNOWNHOSTS_UPLOAD }}
          if_key_exists: replace
          config: |
            Host bastion
              HostName repo.jethome.ru
              User repo
              IdentityFile ~/.ssh/${{ env.RANDOM }}

      - name: Deploy to server
        uses: jethome-iot/actions/repo-upload@master
        with:
          path: '.'
          files: ${{ steps.kernel.outputs.files }}
          hostpath: '/home/repo/armbian'
          branch: ${{ inputs.release }}
          distro: ${{ matrix.linux }}

      - name: test
        if: 0
        run: |
          if ! command -v "lftp" > /dev/null 2>&1; then
             sudo apt-get -y -qq install lftp
          fi
          lftp -u upload, -e "set sftp:connect-program ssh -ax -i $HOME/.ssh/${{ env.RANDOM }}; set net:timeout 4;set net:max-retries 6;mirror -R --include-glob *.deb --no-empty-dirs --parallel=8 --no-perms output/debs/. debs-beta/ ;bye" sftp://users.armbian.com
