name: JH Reset jethome version on version bump

on:
  workflow_dispatch:
    inputs:
      resetfiles:
        required: true
        type: choice
        options:
          - "stable.json"
          - "nightly.json"
          - "stable.json nightly.json"

  push:
    branches:
      - main
    paths:
      - stable.json
      - nightly.json

jobs:
  resetversion:
    name: Reset subversion
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true


    - name: Get changed files for push
      if: github.event_name == 'push'
      id: changed_files_push
      uses: jitterbit/get-changed-files@v1

    - name: Get files from input
      if: github.event_name == 'workflow_dispatch'
      id: changed_files_dispatch
      run: |
        echo "all=${{ github.event.inputs.resetfiles }}" >> $GITHUB_OUTPUT

    - name: Fix versoim
      id: fixversion
      run: |
        for file in ${{ steps.changed_files_push.outputs.all }} ${{ steps.changed_files_dispatch.outputs.all }}; do
          if [[ "$file" == nightly.json ]]; then

            temp=$(mktemp)
            VERSIONM="jh.$(jq -r '.version' nightly-jethome.json | cut -d '.' -f 2 | xargs -n 1 printf '%02d')"
            VER="0.${VERSIONM}.0"
            cat "nightly-jethome.json" | jq ".version |= \"${VER}\"" > "${temp}"
            mv "${temp}" "nightly-jethome.json"
            rm -f "${temp}"

          elif [[ "$file" == stable.json ]]; then

            temp=$(mktemp)
            VERSIONM="jh.$(jq -r '.version' stable-jethome.json | cut -d '.' -f 2 | xargs -n 1 printf '%02d')"
            VER="0.${VERSIONM}.0"
            cat "stable-jethome.json" | jq ".version |= \"${VER}\"" > "${temp}"
            mv "${temp}" "stable-jethome.json"
            rm -f "${temp}"
          fi
        done

    - shell: bash
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name  "GitHub Actions"
        git commit -am "Clean jethome-version"
        git push

